// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCui3BUcSdFuWTIOkNiiyeUlyBdJXlimRg',
    appId: '1:386584073226:web:ca86c08c351658ce203bf3',
    messagingSenderId: '386584073226',
    projectId: 'mydb-531be',
    authDomain: 'mydb-531be.firebaseapp.com',
    storageBucket: 'mydb-531be.firebasestorage.app',
    measurementId: 'G-D3ZESEWKC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfH7uADv5XZMMMqm99kUGpho8DtNLXb6k',
    appId: '1:386584073226:android:67a189d6fba00227203bf3',
    messagingSenderId: '386584073226',
    projectId: 'mydb-531be',
    storageBucket: 'mydb-531be.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9WETJS0QfZihaJr8KP4V47uuiymVlNV0',
    appId: '1:386584073226:ios:238c2e9c856dfb96203bf3',
    messagingSenderId: '386584073226',
    projectId: 'mydb-531be',
    storageBucket: 'mydb-531be.firebasestorage.app',
    iosBundleId: 'com.example.firebase1Data',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9WETJS0QfZihaJr8KP4V47uuiymVlNV0',
    appId: '1:386584073226:ios:238c2e9c856dfb96203bf3',
    messagingSenderId: '386584073226',
    projectId: 'mydb-531be',
    storageBucket: 'mydb-531be.firebasestorage.app',
    iosBundleId: 'com.example.firebase1Data',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCui3BUcSdFuWTIOkNiiyeUlyBdJXlimRg',
    appId: '1:386584073226:web:b630411f2a86b161203bf3',
    messagingSenderId: '386584073226',
    projectId: 'mydb-531be',
    authDomain: 'mydb-531be.firebaseapp.com',
    storageBucket: 'mydb-531be.firebasestorage.app',
    measurementId: 'G-CBD73GN337',
  );
}
