// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBftXnyFO1S-q0OcHl1OK4U6TwPoSXk5lM',
    appId: '1:861554393768:web:b23edd0c7152a63bdf789d',
    messagingSenderId: '861554393768',
    projectId: 'mydb-b43ea',
    authDomain: 'mydb-b43ea.firebaseapp.com',
    storageBucket: 'mydb-b43ea.firebasestorage.app',
    measurementId: 'G-MFTVPJ4C1P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAObqW8pYz8BEny_6tifpyhJjbQUIfe3eI',
    appId: '1:861554393768:android:35aee418770ffe2cdf789d',
    messagingSenderId: '861554393768',
    projectId: 'mydb-b43ea',
    storageBucket: 'mydb-b43ea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDDUP6PH44Mz8jWh9lUTu3jvmknyRsOxM',
    appId: '1:861554393768:ios:e1f10eafaa8c6979df789d',
    messagingSenderId: '861554393768',
    projectId: 'mydb-b43ea',
    storageBucket: 'mydb-b43ea.firebasestorage.app',
    iosBundleId: 'com.example.sabak22FirebaseWithData',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDDUP6PH44Mz8jWh9lUTu3jvmknyRsOxM',
    appId: '1:861554393768:ios:e1f10eafaa8c6979df789d',
    messagingSenderId: '861554393768',
    projectId: 'mydb-b43ea',
    storageBucket: 'mydb-b43ea.firebasestorage.app',
    iosBundleId: 'com.example.sabak22FirebaseWithData',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBftXnyFO1S-q0OcHl1OK4U6TwPoSXk5lM',
    appId: '1:861554393768:web:12b9ffe2214b098fdf789d',
    messagingSenderId: '861554393768',
    projectId: 'mydb-b43ea',
    authDomain: 'mydb-b43ea.firebaseapp.com',
    storageBucket: 'mydb-b43ea.firebasestorage.app',
    measurementId: 'G-49JL40BPEJ',
  );
}
